version: "2.1"

services:

  # ---------------------------
  # Admin

  admin-web:
    container_name: lpa-admin-web
    image: lpa-admin-web
    depends_on:
      - admin-app
    volumes:
      - ./service-admin:/app
    build:
      context: ./
      dockerfile: service-admin/docker/web/Dockerfile
    environment:
      APP_HOST: admin-app
      APP_PORT: 9000
      NGINX_LOG_LEVEL: warn

  admin-app:
    container_name: lpa-admin-app
    image: lpa-admin-app
    build:
      context: ./
      dockerfile: service-admin/docker/app/Dockerfile
    volumes:
      - ./service-admin:/app
#    depends_on:
#      - dynamodb
#      - localstack
#      - local-config
    environment:
      OPG_LPA_STACK_NAME: 'local'
      OPG_LPA_STACK_ENVIRONMENT: 'dev'

      OPG_LPA_ENDPOINTS_API: 'http://api-web'

      OPG_LPA_COMMON_ADMIN_DYNAMODB_TABLE: 'Properties'
      OPG_LPA_COMMON_CRONLOCK_DYNAMODB_TABLE: 'Locks'
      OPG_LPA_COMMON_SESSION_DYNAMODB_TABLE: 'Sessions'

      OPG_LPA_ADMIN_JWT_SECRET: 'test-secret'

      # Local only
      AWS_ACCESS_KEY_ID: '-'
      AWS_SECRET_ACCESS_KEY: '-'

      OPG_LPA_COMMON_DYNAMODB_ENDPOINT: http://dynamodb:8000

      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      #ENABLE_XDEBUG: 'true'
      PHP_IDE_CONFIG: serverName=lpa-admin-app
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1

  admin-composer:
    image: composer
    volumes:
      - ./service-admin:/app
    command:
      - install
      - --prefer-dist
      - --no-suggest
      - --no-interaction
      - --no-scripts
      - --optimize-autoloader

  admin-ssl:
    container_name: lpa-admin-ssl
    image: fsouza/docker-ssl-proxy
    depends_on:
      - admin-web
    ports:
      - 7003:443
    volumes:
      - ./localhost-ssl/certs:/etc/nginx/certs
    environment:
      DOMAIN: 'localhost'
      TARGET_HOST_HEADER: 'localhost:7003'
      SSL_PORT: '443'
      TARGET_HOST: 'admin-web'
      TARGET_PORT: '80'
