name: Generate scan report

on:
  push:
    branches:
      - "master"
      - "main"
  schedule:
    # Every Tuesday, at 3pm UTC
    - cron: '20 15 * * 2'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner@latest
