name: tfsec-pr-commenter

on:
  pull_request:
jobs:
  tfsec:
    name: TFSec Static analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_path: [ 'terraform/environment', 'terraform/account', 'terraform/account_ingress', 'terraform/email' ]
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: tfsec with pr comments
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          working_directory: ${{ matrix.terraform_path }}
          github_token: ${{github.token}}
